input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  # 1. Aşama: Temel Kurumsal Alan Kontrolü (Gümrük)
  if ![txn_id] or ![amt] or ![user] or ![bank] {
    mutate {
      add_field => { "validation_status" => "quarantined" }
      add_tag => [ "missing_fields" ]
    }
  }

  # 2. Aşama: Döviz Formatı Kontrolü (Hatasız Saf Logstash Regex Modu)
  if [currency] {
    if [currency] !~ /^[A-Z]{3}$/ {
      mutate {
        add_field => { "validation_status" => "quarantined" }
        add_tag => [ "invalid_currency_format" ]
      }
    }
  }

  # 3. Aşama: Akıllı İndeks Yönlendirmesi (Smart Routing)
  if [validation_status] == "quarantined" {
    mutate {
      add_field => { "[@metadata][target_index]" => "transactions-quarantine" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "transactions-validated" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "ProductionPassword2026!"
    index => "%{[@metadata][target_index]}"
  }
  stdout { codec => rubydebug }
}
